# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.62.1"
gem "rubocop-github", "~> 0.20.0"
gem "rubocop-minitest", "~> 0.37.0"
gem "rubocop-performance", "~>1.24.0"
gem "rubocop-rails", "~> 2.25"
gem "rubocop-rake", "~> 0.7.0"
gem "rubocop-rspec", "~> 2.31.0"
gem "standard", "~>1.35"
